### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#226]
### Prerequisites: 

* [x] Purchase an iPhone and MacBook
* [x] Create an `LndMobile` implementation that serve dummy data (needs to implement everything that is in [LndMobileInjection.ts](https://github.com/hsjoberg/blixt-wallet/blob/master/src/state/LndMobileInjection.ts)). This is to try out GUI without actually using a real lnd backend. #227
* [x] Separate `LndMobile.java` to different native modules (to make it more clear what iOS really need to implement for an MVP) #225 
* [ ] Upgrade `react-native-async-storage` to version 2 #159 -> Postponed
* [ ] Fix and refactor easy-peasy stores index and Lightning -> Postponed

### GUI:
* [x] Fix eventual GUI bugs
* [x] Replace `react-native-dialogs` in Settings with something that works for iOS
* [x] Fix Blur on iOS (Blur difficult on iOS, current workaround: darken the background)

### Node modules:
* [ ] Replace blur module with something that works for iOS
* [x] Fix react-native-push-notification

### Backend
* [x] Swift lnd gluecode (check how Lightning-app does it)
* [ ] Is Background sync job possible? (semi-dependent on [lnd#4492](https://github.com/lightningnetwork/lnd/issues/4492))

**Comment by hsjoberg** [comment]
Information about background jobs
https://developer.apple.com/documentation/backgroundtasks#overview

Now we must figure out how to properly start up lnd and how to not make the App startup collide with the background job.

**Comment by hsjoberg** [comment]
iOS without backend build implemented in: /2fa8bfa1b0c5c2257b586eb35089291a4af2c6de
Backend implemented in: 960efe8a34d3749d899ad406c3a5e9113b788c95
